name: Build and Release JavaFX Jar

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    if: contains(github.event.head_commit.message, 'v') # Only trigger if commit message contains 'v'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download JavaFX SDK
      run: |
        curl -L https://gluonhq.com/download/javafx-17.0.8-sdk-linux/ -o javafx-sdk.zip
        unzip javafx-sdk.zip -d .

    - name: Compile Java code
      run: |
        mkdir -p outDir
        javac --module-path javafx-sdk/lib --add-modules javafx.controls -d outDir *.java

    - name: Create JAR file
      run: |
        jar cfm keyboard.jar MANIFEST.MF -C outDir .

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: keyboard.jar
        path: keyboard.jar

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: keyboard.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
